# Copyright (c) 2018 Team Foxtrot
# Licensed under MIT License

#autogenerated devise controller
#updated with accessible to prevent cross-model visits

# frozen_string_literal: true

class Staffs::ConfirmationsController < Devise::ConfirmationsController
  #concern to prevent cross-site visits for devise models
  include Accessible
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end
